//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 11:36:22 AM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://pa.ipr.com/policyclient/ws/crystal/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ipr.pa.policyclient.ws.crystal.schemas;
