//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.08.21 at 11:39:11 AM EEST 
//


package com.ipr.pa.policyclient.ws.crystal.schemas.entity;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ipr.pa.policyclient.ws.crystal.schemas.entity package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ipr.pa.policyclient.ws.crystal.schemas.entity
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EntityListMessage }
     * 
     */
    public EntityListMessage createEntityListMessage() {
        return new EntityListMessage();
    }

    /**
     * Create an instance of {@link EntityListMessage.ExtCorrData }
     * 
     */
    public EntityListMessage.ExtCorrData createEntityListMessageExtCorrData() {
        return new EntityListMessage.ExtCorrData();
    }

    /**
     * Create an instance of {@link PropertyList }
     * 
     */
    public PropertyList createPropertyList() {
        return new PropertyList();
    }

    /**
     * Create an instance of {@link EntityList }
     * 
     */
    public EntityList createEntityList() {
        return new EntityList();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

}
